"id": 1,
"type": "MAIN",
"branch_name": "Branch 1",
"address": "Bangalore",
"city": "Bangalore",
"state": "Karntaka",
"pincode": "560100",
"country": "INDIA",
"country_code": "91",
"time_zone": "Asia\/Kolkata",
"branch_email": null,
"branch_phone": null,
"landline": null,
"mode": 1,
"status": 1,